version: '3.7'


services:
  db_postgres:
    container_name: db_postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=redmine
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=redmine
    expose:
      - "5432"
    networks: 
      - redmine
    volumes: 
      - postgre_db:/var/lib/postgresql/data

  redmine:
    container_name: redmine_loc
    image: kyrtsun/custom_redmine
    networks: 
      - nginx_redmine_net
      - redmine
    expose:
      - "3000"
    depends_on:
      - db_postgres
    

networks:
  nginx_redmine_net:
    external: true
  redmine:
    

volumes:
  postgre_db: