version: '3.7'


services:
  db_postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=redmine
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=redmine
    expose:
      - "5432"
    networks:
      - redmine
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      placement:
        constraints:
          - "node.labels.TAG==manager"
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data

  redmine:
    image: kyrtsun/custom_redmine
    restart: unless-stopped
    networks:
      - nginx_redmine_net
      - redmine
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
    expose:
      - "3000"
    depends_on:
      - db_postgres


networks:
  nginx_redmine_net:
    external: true
  redmine:
    driver: overlay