name: Deplot on EC2

on: 
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: log Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Create docker image and push
      run: |
        sudo chmod +x redmine_download.sh
        sudo ./redmine_download.sh
        docker build -t kyrtsun/custom_redmine -f redmine.Dockerfile
        docker push kyrtsun/custom_redmine

    - name: Log in EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}  
        username: ${{ secrets.EC2_USERNAME }}  
        key: ${{ secrets.EC2_KEY }} 
        port: ${{ secrets.EC2_PORT }}

        script: |
          sudo docker stop nginx redmine_loc db_postgres
          sudo docker rm nginx redmine_loc db_postgres
          sudo docker rmi nginx:1.25 kyrtsun/custom_redmine postgres:15-alpine 
          sudo docker rm -r redmine
          sudo docker mkdir redmine && cd redmine
          sudo touch deploy.txt
          sudo snv export https://github.com/Kirtsun/redmine/trunk/docker-compose.yml
          docker-compose up -d 
          wait 
          echo "It works! $(TZ="Europe/Kiev" date "+%A %d-%b-%Y %H:%M:%S %Z")" | sudo tee -a deploy.txt
          
















        
        
