name: Deplot on EC2

on: 
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: log Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Create docker image and push
      run: |
        sudo chmod +x redmine_download.sh
        sudo ./redmine_download.sh
        docker build -t kyrtsun/custom_redmine .
        docker push kyrtsun/custom_redmine

  add_file:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v3

      - name: copy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "red_nginx"
          target: /home/ubuntu/nginx
          overwrite: true

      - name: copy wp docker file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "docker-compose.yml"
          target: /home/ubuntu/redmine
          overwrite: true

  deploy:
    needs: [build, add_file]
    runs-on: ubuntu-latest

    steps:
    - name: Log in EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}

        script: |
          sudo docker stop nginx_nginx_1 redmine_loc db_postgres
          sudo docker rm nginx_nginx_1 redmine_loc db_postgres
          sudo docker rmi nginx:1.25 kyrtsun/custom_redmine postgres:15-alpine
          docker network create nginx_redmine_net
          sudo touch deploy.txt
          cd redmine
          docker-compose up -d 
          wait 
          cd .. &&c cd nginx && sudo docker-compose -up -d
          wait
          cd ..
          echo "Redmine Work! $(TZ="Europe/Kiev" date "+%A %d-%b-%Y %H:%M:%S %Z")" | sudo tee -a deploy.txt
          
















        
        
